### ISSUE TITLE
OK to create a version that supports .net framework 4.5.2? 

### ISSUE THREAD

**Issue by wangyu60** [GovTechSG/csharp-apex-api-security#10]
# Expected Behavior

to make it work in .net framework 4.5.2 environment.

# Current Behavior
Current App server only installed with .Net framework 4.5.2. 

Noticed that the library only made use of one new function from 4.6, DateTimeOffset.ToUnixTimeMilliseconds in the ApiAuthorization.NewTimestamp function 

It can be replaced by the following
            DateTimeOffset dto = new DateTimeOffset(DateTime.UtcNow, TimeSpan.Zero);
            var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            var unixDateTime = Convert.ToInt64((DateTime.UtcNow - epoch).TotalMilliseconds);            
            Logger.LogEnterExit(LoggerBase.Args(unixDateTime));
            return unixDateTime;

then the ApiUtilLib can compile under 4.5.2. 

Noticed that referencing program need to call
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
to avoid "System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel." error. 

# Failure Information (for bugs)

NA

## Steps to Reproduce

NA

## Context

NA

## Failure Logs

NA

**Comment by kelvinwijaya** [comment]
For older framework version, we don't have plan to support this.
But we would suggest that you could fork from our branch and modify the code to fit your use case
