### ISSUE TITLE
Enhance Travis CI configuration to run unit testing

### ISSUE THREAD

**Issue by robincher** [GovTechSG/csharp-apex-api-security#7]
# Expected Behavior

Travis CI to run unit test before build

# Current Behavior

Travis CI shows build success status without running the Unit Test

# Failure Information (for bugs)

N.A

## Steps to Reproduce

N.A

## Context

To enhance current Travis CI config to support unit test running

## Failure Logs
NA.

**Comment by kelvinwijaya** [comment]
Enhanced BaseService class to auto-pull test cases from Github repository: https://github.com/GovTechSG/test-suites-apex-api-security
Also configured travis CI to enable unit-test function through mono nuget package manager and nunit runtime

Some unit test-cases are not passed and will assign to @punjabisingh for fixing
